[debug] [2019-03-25T14:28:49.767Z] ----------------------------------------------------------------------
[debug] [2019-03-25T14:28:49.770Z] Command:       /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/node /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/firebase login
[debug] [2019-03-25T14:28:49.770Z] CLI Version:   6.5.0
[debug] [2019-03-25T14:28:49.770Z] Platform:      linux
[debug] [2019-03-25T14:28:49.770Z] Node Version:  v8.11.3
[debug] [2019-03-25T14:28:49.770Z] Time:          Mon Mar 25 2019 19:58:49 GMT+0530 (IST)
[debug] [2019-03-25T14:28:49.770Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=615465937&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-03-25T14:29:07.261Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-03-25T14:29:07.279Z] Token Fetch Error: Error
    at new FirebaseError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)
[debug] [2019-03-25T14:29:27.050Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-03-25T14:29:27.056Z] Token Fetch Error: Error
    at new FirebaseError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)
[debug] [2019-03-25T14:29:34.730Z] ----------------------------------------------------------------------
[debug] [2019-03-25T14:29:34.733Z] Command:       /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/node /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/firebase login
[debug] [2019-03-25T14:29:34.733Z] CLI Version:   6.5.0
[debug] [2019-03-25T14:29:34.734Z] Platform:      linux
[debug] [2019-03-25T14:29:34.734Z] Node Version:  v8.11.3
[debug] [2019-03-25T14:29:34.734Z] Time:          Mon Mar 25 2019 19:59:34 GMT+0530 (IST)
[debug] [2019-03-25T14:29:34.734Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=587563498&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-03-25T14:29:41.750Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-03-25T14:29:41.769Z] Token Fetch Error: Error
    at new FirebaseError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)
[debug] [2019-03-25T14:30:02.650Z] ----------------------------------------------------------------------
[debug] [2019-03-25T14:30:02.654Z] Command:       /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/node /home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/bin/firebase login
[debug] [2019-03-25T14:30:02.655Z] CLI Version:   6.5.0
[debug] [2019-03-25T14:30:02.655Z] Platform:      linux
[debug] [2019-03-25T14:30:02.655Z] Node Version:  v8.11.3
[debug] [2019-03-25T14:30:02.655Z] Time:          Mon Mar 25 2019 20:00:02 GMT+0530 (IST)
[debug] [2019-03-25T14:30:02.655Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=105750941&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-03-25T14:30:16.378Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-03-25T14:30:16.392Z] Token Fetch Error: Error
    at new FirebaseError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/home/users/mnallinarayanan/.nvm/versions/node/v8.11.3/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)
